CREATE DATABASE pruebaMicroservicios CHARACTER SET utf8 COLLATE utf8_spanish_ci;

USE pruebaMicroservicios;

CREATE TABLE persona (
    id INT AUTO_INCREMENT PRIMARY KEY, 
    nombre VARCHAR(100) NOT NULL DEFAULT '',
    genero CHAR(1) NOT NULL DEFAULT '',
    edad TINYINT UNSIGNED NOT NULL DEFAULT 0,
    identificacion CHAR(13) NOT NULL DEFAULT '',
    direccion VARCHAR(200) NOT NULL DEFAULT '',
    telefono INT(10) UNSIGNED NOT NULL DEFAULT 0,
    estado BIT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8 COLLATE utf8_spanish_ci;

CREATE TABLE cliente (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idPersona INT NOT NULL FOREIGN KEY REFERENCES persona(id),
    constraseña TEXT NOT NULL,
    estado BIT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8 COLLATE utf8_spanish_ci;

CREATE TABLE tipoCuenta (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL DEFAULT '',
    estado BIT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8 COLLATE utf8_spanish_ci;

CREATE TABLE cuenta (
    id INT AUTO_INCREMENT PRIMARY_KEY,
    idTipoCuenta INT NOT NULL FOREIGN KEY REFERENCES tipoCuenta(id),
    saldoInicial INT NOT NULL DEFAULT 0,
    saldoActual INT NOT NULL DEFAULT 0,
    estado BIT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8 COLLATE utf8_spanish_ci;

CREATE TABLE movimientos (
    id INT NOT NULL PRIMARY KEY,
    tipo VARCHAR(30) NOT NULL,
    estado BIT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8 COLLATE utf8_spanish_ci;

CREATE TABLE movimientos (
    id INT NOT NULL PRIMARY KEY,
    idTipoMovimiento INT NOT NULL FOREIGN KEY REFERENCES tipoMovimiento(id),
    idCuenta INT NOT NULL FOREIGN KEY REFERENCES cuenta(id), 
    valor INT NOT NULL,
    saldo INT NOT NULL,
    estado BIT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8 COLLATE utf8_spanish_ci;